### ISSUE TITLE
Authorizer not yet working

### ISSUE THREAD

**Issue by jiahuif** [kubernetes/cel-admission-webhook#2]
```yaml
apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "demo-policy.example.com"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "authorizer.group('apps').resource('deployments').check('create').allowed()"
```
```
$ k create deploy --image=nginx nginx --replicas=2
error: failed to create deployment: admission webhook "cel-shim.example.com" denied the request: deployments.apps "nginx" is forbidden: ValidatingAdmissionPolicy 'demo-policy.example.com' with binding 'demo-binding-test.example.com' denied request: expression 'authorizer.group('apps').resource('deployments').check('create').allowed()' resulted in error: no such attribute: id: 1, names: [authorizer]
```
